version: "3.6"

services:
  category-service:
    image: paxapp/pax-category:latest
    volumes:
      - ".:/app"
    ports:
      - 5002:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
