version: "3.6"

services:
  category-service:
    build:
    context: ./services/category
    dockerfile: Dockerfile
    volumes:
      - "./services/category:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init
