version: "3.6"

services:
  users:
    build:
    context: ./services/users
    dockerfile: Dockerfile-dev
    volumes:
      - "./services/category:/usr/src/app"
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init
